package org.multimediaprototype.oss.dao.model;

import java.util.Date;

public class MediaMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.media_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private Long mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.pic_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.description
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.is_delete
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediamapping.gmt_created
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    private Date gmtCreated;

    private Integer status;

    private String title;

    private Long father;

    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.id
     *
     * @return the value of mediamapping.id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.id
     *
     * @param id the value for mediamapping.id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.media_id
     *
     * @return the value of mediamapping.media_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public Long getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.media_id
     *
     * @param mediaId the value for mediamapping.media_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setMediaId(Long mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.pic_id
     *
     * @return the value of mediamapping.pic_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.pic_id
     *
     * @param picId the value for mediamapping.pic_id
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.description
     *
     * @return the value of mediamapping.description
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.description
     *
     * @param description the value for mediamapping.description
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.is_delete
     *
     * @return the value of mediamapping.is_delete
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.is_delete
     *
     * @param isDelete the value for mediamapping.is_delete
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediamapping.gmt_created
     *
     * @return the value of mediamapping.gmt_created
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediamapping.gmt_created
     *
     * @param gmtCreated the value for mediamapping.gmt_created
     *
     * @mbggenerated Mon Nov 30 19:07:00 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getFather() {
        return father;
    }

    public void setFather(Long father) {
        this.father = father;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}