package org.multimediaprototype.oss.dao.model;

import java.util.Date;

public class OSSFile {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.id
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.userid
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private Long userid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.object_url
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private String objectUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.is_delete
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private Boolean isDelete;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.gmt_created
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private Date gmtCreated;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.object_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private String objectName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.gmt_modify
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private Date gmtModify;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.md5_value
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private String md5Value;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.bucket_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private String bucketName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column oss_file.location
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.id
     * @return  the value of oss_file.id
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.id
     * @param id  the value for oss_file.id
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.userid
     * @return  the value of oss_file.userid
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.userid
     * @param userid  the value for oss_file.userid
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.object_url
     * @return  the value of oss_file.object_url
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public String getObjectUrl() {
        return objectUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.object_url
     * @param objectUrl  the value for oss_file.object_url
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setObjectUrl(String objectUrl) {
        this.objectUrl = objectUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.is_delete
     * @return  the value of oss_file.is_delete
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.is_delete
     * @param isDelete  the value for oss_file.is_delete
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.gmt_created
     * @return  the value of oss_file.gmt_created
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.gmt_created
     * @param gmtCreated  the value for oss_file.gmt_created
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.object_name
     * @return  the value of oss_file.object_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.object_name
     * @param objectName  the value for oss_file.object_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.gmt_modify
     * @return  the value of oss_file.gmt_modify
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.gmt_modify
     * @param gmtModify  the value for oss_file.gmt_modify
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.md5_value
     * @return  the value of oss_file.md5_value
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public String getMd5Value() {
        return md5Value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.md5_value
     * @param md5Value  the value for oss_file.md5_value
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setMd5Value(String md5Value) {
        this.md5Value = md5Value;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.bucket_name
     * @return  the value of oss_file.bucket_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.bucket_name
     * @param bucketName  the value for oss_file.bucket_name
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column oss_file.location
     * @return  the value of oss_file.location
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column oss_file.location
     * @param location  the value for oss_file.location
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    public void setLocation(String location) {
        this.location = location;
    }
}