package org.multimediaprototype.mts.dao.model;

import java.util.Date;

public class MTSJobHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.job_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.job_action
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String jobAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.input_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String inputUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.output_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String outputUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.status
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.gmt_created
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.gmt_modified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.deleted
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.transcode_template_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String transcodeTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.watermark_count
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Integer watermarkCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.gmt_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Date gmtNotified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.status_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String statusNotified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.pipeline_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private String pipelineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mts_job_history.user_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.id
     *
     * @return the value of mts_job_history.id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.id
     *
     * @param id the value for mts_job_history.id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.job_id
     *
     * @return the value of mts_job_history.job_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.job_id
     *
     * @param jobId the value for mts_job_history.job_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.job_action
     *
     * @return the value of mts_job_history.job_action
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getJobAction() {
        return jobAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.job_action
     *
     * @param jobAction the value for mts_job_history.job_action
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setJobAction(String jobAction) {
        this.jobAction = jobAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.input_url
     *
     * @return the value of mts_job_history.input_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getInputUrl() {
        return inputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.input_url
     *
     * @param inputUrl the value for mts_job_history.input_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setInputUrl(String inputUrl) {
        this.inputUrl = inputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.output_url
     *
     * @return the value of mts_job_history.output_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getOutputUrl() {
        return outputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.output_url
     *
     * @param outputUrl the value for mts_job_history.output_url
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setOutputUrl(String outputUrl) {
        this.outputUrl = outputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.status
     *
     * @return the value of mts_job_history.status
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.status
     *
     * @param status the value for mts_job_history.status
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.gmt_created
     *
     * @return the value of mts_job_history.gmt_created
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.gmt_created
     *
     * @param gmtCreated the value for mts_job_history.gmt_created
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.gmt_modified
     *
     * @return the value of mts_job_history.gmt_modified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.gmt_modified
     *
     * @param gmtModified the value for mts_job_history.gmt_modified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.deleted
     *
     * @return the value of mts_job_history.deleted
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.deleted
     *
     * @param deleted the value for mts_job_history.deleted
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.transcode_template_id
     *
     * @return the value of mts_job_history.transcode_template_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getTranscodeTemplateId() {
        return transcodeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.transcode_template_id
     *
     * @param transcodeTemplateId the value for mts_job_history.transcode_template_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setTranscodeTemplateId(String transcodeTemplateId) {
        this.transcodeTemplateId = transcodeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.watermark_count
     *
     * @return the value of mts_job_history.watermark_count
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Integer getWatermarkCount() {
        return watermarkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.watermark_count
     *
     * @param watermarkCount the value for mts_job_history.watermark_count
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setWatermarkCount(Integer watermarkCount) {
        this.watermarkCount = watermarkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.gmt_notified
     *
     * @return the value of mts_job_history.gmt_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Date getGmtNotified() {
        return gmtNotified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.gmt_notified
     *
     * @param gmtNotified the value for mts_job_history.gmt_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setGmtNotified(Date gmtNotified) {
        this.gmtNotified = gmtNotified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.status_notified
     *
     * @return the value of mts_job_history.status_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getStatusNotified() {
        return statusNotified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.status_notified
     *
     * @param statusNotified the value for mts_job_history.status_notified
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setStatusNotified(String statusNotified) {
        this.statusNotified = statusNotified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.pipeline_id
     *
     * @return the value of mts_job_history.pipeline_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public String getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.pipeline_id
     *
     * @param pipelineId the value for mts_job_history.pipeline_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setPipelineId(String pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mts_job_history.user_id
     *
     * @return the value of mts_job_history.user_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mts_job_history.user_id
     *
     * @param userId the value for mts_job_history.user_id
     *
     * @mbggenerated Thu Nov 26 17:14:00 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}