package org.multimediaprototype.oss.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.multimediaprototype.oss.dao.model.OSSFile;
import org.springframework.stereotype.Repository;

@Repository
public interface OSSFileMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    Long insert(OSSFile record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    Long insertSelective(OSSFile record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    OSSFile selectByPrimaryKey(Long id);
    
    OSSFile getOssdetailbykey(String key, Long userid);


    List<OSSFile> selectByKey(Long id,Integer offset);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    Long updateByPrimaryKeySelective(OSSFile record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table oss_file
     * @mbggenerated  Thu Nov 26 10:28:49 CST 2015
     */
    Long updateByPrimaryKey(OSSFile record);

    OSSFile getByUrl(@Param("url") String url);
}